
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 369369rt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        ##use_sql_comments : true
        format_sql: true
        ##default_batch_fetch_size : 100
    ##show-sql: true

logging.level:
  org.hibernate.SQL: debug